# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua


dwindle {
  preserve_split = true
}

# ------ Startups ------
exec-once = waybar
exec-once = dunst
exec-once = kime

env = GTK_IM_MODULE,kime
env = QT_IM_MODULE,kime
env = XMODIFIERS,@im=kime

#############
## KEYMAPS ##
#############
$mainMod = SUPER
$terminal = ghostty
$menu = hyprlauncher
$browser= zen-browser

# ------ Apps ------
bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, V, togglefloating,
#bind = $mainMod, O, togglesplit,
bind = $mainMod, R, exec, $menu

# ------ screenshot ------
bind = $mainMod_CTRL, Q, exec, hyprshot -m output  # screenshot whole screen
bind = $mainMod_CTRL, W, exec, hyprshot -m output  # screenshot open window
bind = $mainMod_CTRL, E, exec, hyprshot -m output  # screenshot selected region

# ----- volume, bright ------
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-
bind = , XF86MonBrightNessUp, exec, brightnessctl set 10%+
bind = , XF86MonBrightNessDown, exec, brightnessctl set 10%-

# ------ Windows management ------
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen,

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $mainMod_SHIFT, h, movewindow, l
bind = $mainMod_SHIFT, l, movewindow, r
bind = $mainMod_SHIFT, k, movewindow, u
bind = $mainMod_SHIFT, j, movewindow, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod_SHIFT, 1, movetoworkspace, 1
bind = $mainMod_SHIFT, 2, movetoworkspace, 2
bind = $mainMod_SHIFT, 3, movetoworkspace, 3
bind = $mainMod_SHIFT, 4, movetoworkspace, 4
bind = $mainMod_SHIFT, 5, movetoworkspace, 5
bind = $mainMod_SHIFT, 6, movetoworkspace, 6
bind = $mainMod_SHIFT, 7, movetoworkspace, 7
bind = $mainMod_SHIFT, 8, movetoworkspace, 8
bind = $mainMod_SHIFT, 9, movetoworkspace, 9

bind = $mainMod_CTRL, h, resizeactive, -20   0
bind = $mainMod_CTRL, l, resizeactive,  20   0
bind = $mainMod_CTRL, k, resizeactive,   0 -20
bind = $mainMod_CTRL, j, resizeactive,   0  20
